task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# 核心修改 1：类别数量改为 2 (烟雾 + 火焰)
num_classes: 2 
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    # 核心修改 2：指向训练集图片文件夹
    img_folder: /root/autodl-tmp/D-Fire/data/train/images
    # 核心修改 3：指向训练集 JSON 标注文件
    ann_file: /root/autodl-tmp/D-Fire/data/train/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    # 核心修改 4：指向验证集图片文件夹
    img_folder: /root/autodl-tmp/D-Fire/data/val/images
    # 核心修改 5：指向验证集 JSON 标注文件
    ann_file: /root/autodl-tmp/D-Fire/data/val/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
